---
title: "ERHS535_HW_5"
author: "Daniel Dean"
date: "11/20/2019"
output:
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

```{r Data setup, include = FALSE}
#Loading packages
library(readr)
library(dplyr)
library(lubridate)
library(stringr)
library(ggplot2)
library(tigris)
library(forcats)
library(sf)
library(ggthemes)


#Importing homicide data from Washington Post, with pre-filtering

homicides <- read_csv("https://raw.githubusercontent.com/washingtonpost/data-homicides/master/homicide-data.csv") %>%
  mutate(reported_date = str_replace(string = reported_date, pattern = "201511018", replacement =  "20151018"),
         reported_date = str_replace(string = reported_date, pattern = "201511105", replacement =  "20151018"),
         reported_date = ymd(reported_date)
         ) %>% #corrected two apparent typos (guessed correct month from order) before converting to date format
  mutate_at(.vars = c('victim_race', 'victim_sex', 'city', 'state', 'disposition'), .funs = as.factor) %>%
  mutate(victim_age = as.numeric(victim_age)) %>%
  mutate(disposition = fct_collapse(disposition,
                Solved = "Closed by arrest",
               Unsolved = c("Closed without arrest","Open/No arrest")
               ))

#Limiting scope and converting to sf object

homicides_map_omaha <- homicides %>%
  filter(city == "Omaha") %>%
  mutate(victim_race = fct_lump(victim_race, n=4, other_level = "Other")) %>%
  st_as_sf(coords = c("lon","lat")) %>%
  st_set_crs(4269)

#Importing census tracts:
omaha_tracts <- tracts("NE", county = "Douglas") %>%
  st_as_sf() %>%  
  st_set_crs(4269)


```


```{r include = FALSE}

ggplot() + 
  geom_sf(data = omaha_tracts, fill = "white") + 
  geom_sf(data = homicides_map_omaha, aes(fill = victim_race), shape = 23, color = 'black') +
  facet_wrap(.~disposition, ncol = 2) +
  scale_fill_tableau() +
  labs(title = "Omaha, NE Homicides (2007-2017)", subtitle = "Organized by Outcome and Location (US Census Tracts)", 
       fill = "Race of Victim") +
  theme_map() +
  theme(legend.position = 'top', strip.text.x = element_text(size = 15, face = 'bold'),
        plot.title = element_text(size = 15, face = 'bold'))


```

```{r plotting}
#Plotting:


ggplot() + 
  geom_sf(data = omaha_tracts, fill = "white") + 
  geom_sf(data = homicides_map_omaha, aes(fill = victim_race), shape = 23, color = 'grey') +
  facet_wrap(.~disposition, nrow = 2) +
  scale_fill_tableau() +
  labs(title = "Omaha, NE Homicides (2007-2017)",
       subtitle = "Organized by Outcome and Location (US Census Tracts)", 
       fill = "Race of Victim") +
  theme_map() +
  theme(legend.position = 'bottom', strip.text.x = element_text(size = 15, face = 'bold'),
        plot.title = element_text(size = 15, face = 'bold'))

```

